version: '3'
services:
  repnotes-ami-v2:
    build:
      context: .
    image: opsenterprise/dev-repnotes-ami-v2
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/repnotes-ami-v2/default.conf  
    restart: always 
    ports:
      - '3034:80' 